const CLUBS={"Arsenal":"8430.png","Aston Villa":"8429.png","Bristol City":"8434.png","Chelsea":"8400.png","Everton":"8437.png","Leicester City":"8399.png","Liverpool":"8398.png","Manchester City":"8397.png","Manchester United":"8396.png","Newcastle":"8395.png","Nottingham Forest":"8393.png","Sheffield United":"8439.png","Southampton":"8442.png","Stoke City":"8433.png","Tottenham":"8392.png","Watford":"8440.png","Wolves":"8391.png","Ipswich Town":"8435.png","Norwich City":"8443.png"};
const COMP={"Premier League":"8450.png","Championship":"8447.png","FA Cup":"8448.png","Community Shield":"8449.png"};
const P=[['inicio','🏠 Inicio'],['liga','👑 Premier League'],['champ','🥈 Championship'],['fa','🏆 FA Cup'],['shield','🛡️ Community Shield'],['clubes','⚽ Clubes'],['cartas','🪪 Cartas'],['chat','💬 Chat general'],['videos','🎬 Vídeos'],['updates','📰 Updates'],['admin','🛠️ Admin Editor'],['donar','💜 Donaciones']];
const nav=document.getElementById('nav'),dn=document.getElementById('drawerNav');P.forEach(x=>{let b=document.createElement('button');b.className='navbtn';b.textContent=x[1];b.onclick=()=>show(x[0]);nav.appendChild(b);let d=b.cloneNode(true);d.className='drawerbtn';d.onclick=()=>show(x[0]);dn.appendChild(d)});
const img=x=>'assets/'+x,esc=x=>String(x||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function shell(id,title,desc,body){return `<section class="page" id="p-${id}"><div class="hero"><span class="tag">PREMIER LUEGE • SF27</span><h1>${title}</h1><p>${desc}</p></div>${body}</section>`}
function render(){document.getElementById('app').innerHTML=[
shell('inicio','Premier Luege SF27','El hub retro-moderno de tu liga: clubes, copas, cartas, comunidad, vídeos y administración.',`<div class="grid"><div class="card"><h2>🎮 SF27</h2><p class="muted">Prueba el juego oficial de la liga.</p><a class="btn" target="_blank" href="https://www.roblox.com/es/games/83009840994296/SF27">Abrir Roblox</a></div><div class="card"><h2>💬 Comunidad</h2><p class="muted">Habla y comparte opiniones.</p><button class="btn ghost" onclick="show('chat')">Entrar al chat</button></div><div class="card"><h2>🎬 Vídeos</h2><p class="muted">Busca creadores y contenido.</p><button class="btn ghost" onclick="show('videos')">Ver vídeos</button></div></div>`),
shell('liga','Premier League','Competición principal: tabla, jornadas y resultados listos para conectar al Admin Editor.',`<div class="grid"><div class="card span8"><h2>👑 La élite</h2><p class="muted">Gestiona clubes y partidos desde la zona administrativa.</p><a class="btn" target="_blank" href="https://discord.gg/rY9eCGvN7">Discord de la liga</a></div><div class="card"><img style="width:100%;height:160px;object-fit:contain" src="${img(COMP['Premier League'])}"></div></div>`),
shell('champ','Championship','Segunda categoría y camino a la élite.',`<div class="card"><img style="width:120px;height:120px;object-fit:contain" src="${img(COMP.Championship)}"><h2>Championship</h2></div>`),
shell('fa','FA Cup','Torneo de eliminación directa.',`<div class="card"><img style="width:120px;height:120px;object-fit:contain" src="${img(COMP['FA Cup'])}"><h2>FA Cup</h2></div>`),
shell('shield','Community Shield','Copa especial para abrir la temporada.',`<div class="card"><img style="width:120px;height:120px;object-fit:contain" src="${img(COMP['Community Shield'])}"><h2>Community Shield</h2></div>`),
shell('clubes','Clubes','Los escudos suministrados para la primera actualización.',`<div class="clubgrid">${Object.entries(CLUBS).map(([n,f])=>`<div class="club"><img src="${img(f)}"><strong>${esc(n)}</strong></div>`).join('')}</div>`),
shell('cartas','Cartas Base','Crea una carta inicial y guarda sus datos localmente. El Admin puede convertirse después en sistema global.',`<div class="grid"><div class="card span6"><div class="card-preview"><div class="rating" id="vr">70</div><b id="vp">CF</b><div class="player" id="vn">NUEVO JUGADOR</div><div class="stats">${['PAC','SHO','PAS','DRI','DEF','PHY'].map(s=>`<div class="stat">${s} <span id="v${s}">70</span></div>`).join('')}</div></div></div><div class="card span6"><h2>Editor de carta</h2>${['nombre','pos','media','pac','sho','pas','dri','def','phy'].map(k=>`<input class="input ci" data-k="${k}" placeholder="${k.toUpperCase()}" value="${k==='nombre'?'Nuevo Jugador':k==='pos'?'CF':70}" style="margin:5px 0">`).join('')}<button class="btn" onclick="saveCard()">Guardar</button></div></div>`),
shell('chat','Chat general','Chat grande para miembros. El nombre queda guardado en este navegador y se puede cambiar. Para chat global real se conecta el backend.',`<div class="card chat"><div class="messages" id="msgs"></div><div class="chatbar"><input class="input" id="ct" placeholder="Escribe un mensaje..."><button class="btn" onclick="sendMsg()">Enviar</button></div><div class="note">Usuario: <b id="cu"></b> · <button class="btn ghost" onclick="changeUser()">Cambiar usuario</button></div></div>`),
shell('videos','Vídeos','Busca un canal o tema. Si el backend está activo, usa YouTube Data API; si no, abre la búsqueda oficial.',`<div class="card"><div class="search"><input class="input" id="yt" placeholder="Ejemplo: Davo Xeneize"><button class="btn" onclick="ytSearch()">🔎 Buscar</button></div><div id="yr"></div><p class="note">La API key nunca debe estar en app.js; se configura como variable de entorno en el servidor.</p></div>`),
shell('updates','Updates','Novedades del proyecto.',`<div class="grid"><div class="card"><span class="tag">UPDATE 1.0</span><h2>🚀 Nueva interfaz</h2><p class="muted">Fondo degradado, menú moderno retro, animaciones, clubes, copas, cartas, chat y vídeos.</p></div><div class="card"><span class="tag">FULL</span><h2>🛠️ Backend preparado</h2><p class="muted">Servidor Node incluido para YouTube y futuras funciones globales.</p></div></div>`),
shell('admin','Admin Editor','Zona central para gestionar la liga. Esta edición trae la interfaz; los cambios globales se guardan mediante el backend cuando lo conectes a una base de datos.',`<div class="grid"><div class="card span6"><h2>🪪 Cartas</h2><p class="muted">Crear y editar cartas base.</p><button class="btn" onclick="show('cartas')">Abrir editor</button></div><div class="card span6"><h2>⚽ Clubes</h2><p class="muted">Escudos centralizados en app.js para actualizar fácilmente.</p></div><div class="card span6"><h2>📊 Partidos y tabla</h2><p class="muted">Estructura preparada para conectar resultados y posiciones.</p></div><div class="card span6"><h2>🔐 Seguridad</h2><p class="muted">El servidor usa una contraseña de administrador en variable de entorno. No pongas secretos en GitHub.</p></div></div>`),
shell('donar','Donaciones','Apartado preparado para apoyar el proyecto. Añade tu PayPal.me cuando lo tengas.',`<div class="card"><h2>💜 Apoya el proyecto</h2><p class="muted">Aquí irá tu enlace PayPal.me.</p><button class="btn" onclick="alert('Añade tu PayPal.me en la variable donationUrl de app.js')">Configurar PayPal.me</button></div>`)
].join('')}
function show(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.getElementById('p-'+id).classList.add('active');document.getElementById('drawer').classList.remove('open');if(id==='chat')loadChat();window.scrollTo({top:0,behavior:'smooth'})}
function saveCard(){let v={};document.querySelectorAll('.ci').forEach(x=>v[x.dataset.k]=x.value);localStorage.pl_card=JSON.stringify(v);alert('Carta guardada en este navegador.')}function loadChat(){let u=localStorage.pl_user;if(!u){u=prompt('Elige tu nombre de usuario:')||'Invitado';localStorage.pl_user=u}document.getElementById('cu').textContent=u;let m=JSON.parse(localStorage.pl_msgs||'[]');document.getElementById('msgs').innerHTML=m.map(x=>`<div class="msg"><b>${esc(x.u)}</b><div>${esc(x.t)}</div></div>`).join('');document.getElementById('msgs').scrollTop=999999}function sendMsg(){let t=document.getElementById('ct').value.trim();if(!t)return;let m=JSON.parse(localStorage.pl_msgs||'[]');m.push({u:localStorage.pl_user||'Invitado',t});localStorage.pl_msgs=JSON.stringify(m.slice(-200));document.getElementById('ct').value='';loadChat()}function changeUser(){let u=prompt('Nuevo nombre de usuario:',localStorage.pl_user||'Invitado');if(u){localStorage.pl_user=u;loadChat()}}
async function ytSearch(){let q=document.getElementById('yt').value.trim(),r=document.getElementById('yr');if(!q)return;r.innerHTML='<p class="muted">Buscando...</p>';try{let x=await fetch('/api/youtube/search?q='+encodeURIComponent(q));if(!x.ok)throw 0;let d=await x.json();r.innerHTML=(d.items||[]).map(v=>`<div class="card" style="margin-top:10px"><h3>${esc(v.title)}</h3><p class="muted">${esc(v.channelTitle)}</p><a class="btn" target="_blank" href="https://www.youtube.com/watch?v=${encodeURIComponent(v.videoId)}">▶️ Ver vídeo</a></div>`).join('')||'<p class="muted">Sin resultados.</p>'}catch(e){let u='https://www.youtube.com/results?search_query='+encodeURIComponent(q);r.innerHTML=`<div class="card"><h3>🔎 ${esc(q)}</h3><p class="muted">Backend/API no conectado.</p><a class="btn" target="_blank" href="${u}">Abrir búsqueda de YouTube</a></div>`}}
document.getElementById('hamb').onclick=()=>document.getElementById('drawer').classList.add('open');document.getElementById('close').onclick=()=>document.getElementById('drawer').classList.remove('open');document.getElementById('theme').onclick=()=>document.body.classList.toggle('light');document.getElementById('profile').onclick=()=>{show('chat');setTimeout(changeUser,100)};document.getElementById('year').textContent=new Date().getFullYear();render();show('inicio');
